<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="generator" content="Hugo 0.31.1" />

  <title>LiDAR Analysis of Kaikoura NZ &middot; Kim Fitter</title>

  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/pure-min.css">

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-min.css">
  <!--<![endif]-->

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/side-menu-old-ie.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/side-menu.css">
  <!--<![endif]-->

  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/blackburn.css">

  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

 
  

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/androidstudio.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  
  <script>hljs.initHighlightingOnLoad();</script>
  

  <link rel="shortcut icon" href="https://kimnewzealand.github.io/img/favicon.ico" type="image/x-icon" />

  
  

</head>


<body>
<div id="layout">

  
<a href="#menu" id="menuLink" class="menu-link">
  
  <span></span>
</a>
<div id="menu">

  
  <a class="pure-menu-heading brand" href="https://kimnewzealand.github.io/">Kim Fitter</a>


  <div class="pure-menu">
    <ul class="pure-menu-list">
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://kimnewzealand.github.io/"><i class='fa fa-home fa-fw'></i>Home</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://kimnewzealand.github.io/about/"><i class='fa fa-user fa-fw'></i>About</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://kimnewzealand.github.io/post/"><i class='fa fa-list fa-fw'></i>Blog Archive</a>
      
        </li>
      
    </ul>
  </div>

  <div class="pure-menu social">
  <ul class="pure-menu-list">

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://twitter.com/kim_fitter" target="_blank"><i class="fa fa-twitter-square fa-fw"></i>Twitter</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://github.com/kimnewzealand" target="_blank"><i class="fa fa-github-square fa-fw"></i>GitHub</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

  </ul>
</div>


  <div>
  <div class="small-print">
    <small>Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)</small>
  </div>
  <div class="small-print">
    <small>Built with&nbsp;<a href="https://gohugo.io/" target="_blank">Hugo</a></small>
    <small>Theme&nbsp;<a href="https://github.com/yoshiharuyamashita/blackburn" target="_blank">Blackburn</a></small>
  </div>
</div>

</div>


  <div id="main">


<div class="header">
  <h1>LiDAR Analysis of Kaikoura NZ</h1>
  <h2></h2>
</div>
<div class="content">

  <div class="post-meta">

  <div>
    <i class="fa fa-calendar fa-fw"></i>
    <time>07 Dec 2018</time>
  </div>

  

  

  
  
  
  <div>
    <i class="fa fa-tags fa-fw"></i>
    
      <a class="post-taxonomy-tag" href="https://kimnewzealand.github.io/tags/r">R</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="https://kimnewzealand.github.io/tags/gis">GIS</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="https://kimnewzealand.github.io/tags/eda">EDA</a>
    
  </div>
  
  

</div>

  <script src="https://kimnewzealand.github.io/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="https://kimnewzealand.github.io/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="https://kimnewzealand.github.io/rmarkdown-libs/leaflet/leaflet.css" rel="stylesheet" />
<script src="https://kimnewzealand.github.io/rmarkdown-libs/leaflet/leaflet.js"></script>
<link href="https://kimnewzealand.github.io/rmarkdown-libs/leafletfix/leafletfix.css" rel="stylesheet" />
<script src="https://kimnewzealand.github.io/rmarkdown-libs/Proj4Leaflet/proj4-compressed.js"></script>
<script src="https://kimnewzealand.github.io/rmarkdown-libs/Proj4Leaflet/proj4leaflet.js"></script>
<link href="https://kimnewzealand.github.io/rmarkdown-libs/rstudio_leaflet/rstudio_leaflet.css" rel="stylesheet" />
<script src="https://kimnewzealand.github.io/rmarkdown-libs/leaflet-binding/leaflet.js"></script>
<script src="https://kimnewzealand.github.io/rmarkdown-libs/leaflet-providers/leaflet-providers.js"></script>
<script src="https://kimnewzealand.github.io/rmarkdown-libs/leaflet-providers-plugin/leaflet-providers-plugin.js"></script>


<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#data%20overview">Data Overview</a></li>
<li><a href="#load-data">Load Data</a></li>
<li><a href="#data-manipulation">Data Manipulation</a></li>
<li><a href="#data-exploration">Data Exploration</a></li>
<li><a href="#data-visualisation">Data Visualisation</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The <a href="https://www.geonet.org.nz/earthquake/2016p858000">Kaikoura earthquake</a> happened just after midnight on 14 November 2016.</p>
<p>After reading this article <a href="https://www.stuff.co.nz/national/87171157/Astonishing-Nasa-photos-show-Kaikoura-land-raised-by-earthquake">Astonishing Nasa photos show Kaikoura land raised by earthquake</a> I thought it would interesting to look at what open data is available to view the land changes from the article.</p>
<p>This analysis has the following objectives:</p>
<ul>
<li>Import, manipulate and visualise both vector and raster spatial data</li>
<li>Use different spatial extents</li>
<li>Use LiDAR remote sensing open data</li>
<li>Explore and use different Coordinate Reference System formats including proj.4, EPSG and WKT</li>
<li>Reproject vector and raster data to different CRS</li>
</ul>
<pre class="r"><code># Tidyverse metapackage
library(tidyverse)
# Package for reading spatial datasets
library(rgdal)
library(raster)
# Package for manipulating and plotting spatial data
library(sf)
# Package for downloading OSM data
library(osmdata)
# Package for plotting OSM basemap
library(osmplotr)
# Package for interactive maps
library(leaflet)
# Package for raster vis
library(rasterVis)</code></pre>
</div>
<div id="data-overview" class="section level2">
<h2>Data Overview</h2>
<div id="lidar-data" class="section level3">
<h3>LiDAR Data</h3>
<p>LiDAR or Light Detection and Ranging is an active remote sensing system that can be used to measure vegetation height across wide areas.</p>
<p><a href="https://data.linz.govt.nz/layer/3542-canterbury-kaikoura-lidar-1m-dem-2012/">LiDAR DEM data from before the earthquakes</a> is available for Kaikoura, Canterbury, New Zealand 2012:</p>
<blockquote>
<p>Lidar was captured for Environment Canterbury Regional Council by Aerial Surveys in 2012. Note that this capture was prior to the significant vertical and horizontal displacements from the 2016 Kaikoura earthquakes. The datasets were generated by Aerial Surveys and their subcontractors. The survey area includes the Kaikoura township area and adjacent coastal strips. Data management and distribution is by Land Information New Zealand.</p>
</blockquote>
</div>
</div>
<div id="load-data" class="section level2">
<h2>Load Data</h2>
<div id="create-a-kaikoura-bounding-box" class="section level3">
<h3>Create a Kaikoura Bounding Box</h3>
<p>Let’s create a bounding box or bbox which can be described as the spatial extent of the area of Kaikoura we want to initially analyse.</p>
<p>Create a bbox using the getbb function from <a href="https://cran.r-project.org/web/packages/osmdata/index.html">osmdata</a> R package of Kaikoura town.</p>
<pre class="r"><code># Get longitude and latitude coordinates for a Kaikoura bbox using osmdata package
kaikoura_bbox&lt;- getbb(&quot;Kaikoura&quot;)
# Take a look at the CRS
crs(kaikoura_bbox)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code># Plot the bbox 
plot(kaikoura_bbox)</code></pre>
<p><img src="https://kimnewzealand.github.io/post/KaikouraLIDARanalysis_files/figure-html/kaikoura%20bbox-1.png" width="672" /></p>
<p>Currently this bbox object has no CRS and it consists of two points? Ideally we would like a polygon shape. Let’s get the bbox as an <a href="https://cran.r-project.org/web/packages/sf/index.html">sf</a> object after following the package <a href="https://rdrr.io/cran/osmdata/man/getbb.html">examples</a>.</p>
<pre class="r"><code># Get Kaikoura bbox polygon seeting the format to sf
kaikoura_bbox_sf&lt;- osmdata::getbb(&quot;Kaikoura&quot;, format_out = &quot;sf_polygon&quot;)</code></pre>
<pre><code>## No polygonal boundary for Kaikoura</code></pre>
<pre class="r"><code># View the kaikoura_bbox_sf
kaikoura_bbox_sf</code></pre>
<pre><code>## Simple feature collection with 1 feature and 0 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 173.6404 ymin: -42.44037 xmax: 173.7204 ymax: -42.36037
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
##                         geometry
## 1 POLYGON ((173.6404 -42.3603...</code></pre>
<pre class="r"><code># We can check the bbox extent of our sf object using st_bbox function
st_bbox(kaikoura_bbox_sf)</code></pre>
<pre><code>##      xmin      ymin      xmax      ymax 
## 173.64036 -42.44037 173.72036 -42.36037</code></pre>
<pre class="r"><code># Check the crs of the bbox
st_crs(kaikoura_bbox_sf)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code># Now plot the bbox sf object using ggplot and geom_sf to check that it is a box/pologon
ggplot(kaikoura_bbox_sf)+
      geom_sf()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/KaikouraLIDARanalysis_files/figure-html/kaikoura%20bbox%20take%202-1.png" width="672" /></p>
<p>The Coordinate Reference System (CRS) is the <a href="http://openstreetmapdata.com/info/projections">WGS84 (EPSG 4326) system</a>:</p>
<blockquote>
<p>OpenStreetMap uses the WGS84 spatial reference system used by the Global Positioning System (GPS). It uses geographic coordinates between -180° and 180° longitude and -90° and 90° latitude. So this is the “native” OSM format.</p>
</blockquote>
<p>Let’s plot this bbox using <a href="https://cran.r-project.org/web/packages/leaflet/index.html">leaflet</a> R package to see where it is on a map.</p>
<pre class="r"><code># Map Kaikoura using leaflet and the bbox
kaikoura_bbox_sf %&gt;% 
      leaflet() %&gt;% 
      addTiles() %&gt;%
      addPolylines()</code></pre>
<div id="htmlwidget-1" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addPolylines","args":[[[[{"lng":[173.6403614,173.7203614,173.7203614,173.6403614,173.6403614],"lat":[-42.3603723,-42.3603723,-42.4403723,-42.4403723,-42.3603723]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":false,"fillColor":"#03F","fillOpacity":0.2,"smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[-42.4403723,-42.3603723],"lng":[173.6403614,173.7203614]}},"evals":[],"jsHooks":[]}</script>
<p>Longitude and latitude is useful for navigation and locating places on a map but not for data analysis or measurement so we need use a consistent map projection for all our data.</p>
<p>Maps of New Zealand used for data analysis use <a href="https://lris.scinfo.org.nz/p/lris_faqs/EPSG:2193">New Zealand Transverse Mercator / New Zealand Geodetic Datum 2000 (EPSG:2193)</a>.</p>
<p>Now we want to project the bbox to <a href="http://spatialreference.org/ref/epsg/nzgd2000-new-zealand-transverse-mercator-2000/">EPSG 2193</a> which is in metres instead of degrees. We will create a Well-known text (WKT) polygon to export to and load in QGIS to visualise the raster data sets within this bbox.</p>
<pre class="r"><code># Change the Epsg of the bbox to EPSG 2193 for NZ using st_transform
kaikoura_bbox_sf_2193&lt;- st_transform(kaikoura_bbox_sf,2193)
# Check the crs of the transformed bbox
st_crs(kaikoura_bbox_sf_2193)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 2193 
##   proj4string: &quot;+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs&quot;</code></pre>
<pre class="r"><code># We can check the bbox extent  of our reprojected sf object in metres using st_bbox function
st_bbox(kaikoura_bbox_sf_2193)</code></pre>
<pre><code>##    xmin    ymin    xmax    ymax 
## 1652666 5301077 1659321 5310012</code></pre>
<pre class="r"><code># Create a WKT from the bbox class using sf package
Kaikoura_WKT &lt;- st_as_text(st_geometry(kaikoura_bbox_sf_2193)) %&gt;%  
      data.frame()
# Write the WKT to file to be imported into QGIS
# write_csv(Kaikoura_WKT,&quot;kaikoura_wkt.csv&quot;)</code></pre>
</div>
<div id="import-the-lidar-data" class="section level3">
<h3>Import the LiDAR Data</h3>
<p>Import the LiDAR data in raster or gridded format using the <a href="https://cran.r-project.org/web/packages/raster/index.html">raster</a> R package. We will first inspect one sample tif file as there are a large number of files from the downloaded zip file.</p>
<p>The GeoTIFF format contains a set of embedded or tif tags with metadata about the raster data. We can use the function GDALinfo() from <a href="https://cran.r-project.org/web/packages/rgdal/index.html">rgdal</a> R package to get information ie metadata about our raster data before we read that data into R. It is ideal to do this before importing your data.</p>
<pre class="r"><code># Preview metadata using GDALinfo from rgdal package
GDALinfo(&quot;data/DEM_BT27_2012_1000_4343.tif&quot;)</code></pre>
<pre><code>## rows        720 
## columns     480 
## bands       1 
## lower left origin.x        1656160 
## lower left origin.y        5303040 
## res.x       1 
## res.y       1 
## ysign       -1 
## oblique.x   0 
## oblique.y   0 
## driver      GTiff 
## projection  +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000
## +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m
## +no_defs 
## file        data/DEM_BT27_2012_1000_4343.tif 
## apparent band summary:
##    GDType hasNoDataValue NoDataValue blockSize1 blockSize2
## 1 Float32           TRUE       -9999        256        256
## apparent band statistics:
##   Bmin  Bmax    Bmean      Bsd
## 1 2.88 75.63 36.40099 22.00292
## Metadata:
## AREA_OR_POINT=Area</code></pre>
<pre class="r"><code># Import raster sample file with raster package
lidar_sample &lt;- raster(x = &quot;data/DEM_BT27_2012_1000_4343.tif&quot;)
# Take a look at the class of this object
class(lidar_sample)</code></pre>
<pre><code>## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;</code></pre>
<pre class="r"><code># Check the CRS of the lidar sample file
crs(lidar_sample)</code></pre>
<pre><code>## CRS arguments:
##  +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000
## +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m
## +no_defs</code></pre>
<p>The file is a “RasterLayer”, a single layer of raster data and the CRS is in proj.4 format with <a href="https://proj4.org/operations/projections/tmerc.html">the transverse Mercator projection</a>:</p>
<ul>
<li>proj=tmerc</li>
<li>k=0.9996 Scale factor. Determines scale factor used in the projection.</li>
<li>x_0=1600000 False easting</li>
<li>y_0=10000000 False northing</li>
<li>units=m: the units for the coordinates are in METERS</li>
<li>ellps=GRS80: the ellipsoid (how the earth’s roundness is calculated) for the data is GRS80</li>
</ul>
<p>Each LiDAR point has an elevation value, which adds a third dimension to the spatial data.</p>
<pre class="r"><code># Create a list of the file paths of the tif files and select rasters DEM_BT27_2012_1000_434*.tif based on a more detailed area we look for to analyse based on QGIS analysis using glob2rx function https://stackoverflow.com/questions/14360174/list-files-pattern-argument-in-r-extended-regular-expression-use
list_tifs &lt;- list.files(path = &quot;data/&quot;, pattern = glob2rx(&quot;DEM_BT27_2012_1000_434*.tif&quot;), full.names = TRUE)
# Create a list of raster layers from the list_tifs
raster_list &lt;- map(list_tifs, raster)
# Take a look at the first raster in the list
raster_list[[1]]</code></pre>
<pre><code>## class       : RasterLayer 
## dimensions  : 720, 480, 345600  (nrow, ncol, ncell)
## resolution  : 1, 1  (x, y)
## extent      : 1655200, 1655680, 5303040, 5303760  (xmin, xmax, ymin, ymax)
## coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
## data source : C:\Users\Home\Documents\blogdown_source\content\post\data\DEM_BT27_2012_1000_4341.tif 
## names       : DEM_BT27_2012_1000_4341 
## values      : -0.75, 3.98  (min, max)</code></pre>
</div>
</div>
<div id="data-manipulation" class="section level2">
<h2>Data Manipulation</h2>
<p>Now let’s manipulate the data that we have imported. First merge the LiDAR rasters.</p>
<pre class="r"><code># Now use the raster merge function to merge the raster layers of the lidar data
kaikoura_lidar &lt;- do.call(raster::merge, c(raster_list, tolerance = 1))
# Write the merged raster as object for QGIS
# writeRaster(kaikoura_lidar,&quot;kaikoura_lidar.tiff&quot;)</code></pre>
<p>Let’s check the extents of the raster sets.</p>
<pre class="r"><code># Check the extent of the lidar raster
extent(kaikoura_lidar)</code></pre>
<pre><code>## class       : Extent 
## xmin        : 1655200 
## xmax        : 1659520 
## ymin        : 5303040 
## ymax        : 5303760</code></pre>
<p>Next we will create and visualise an Area of Interest (AOI) from the LiDAR rasters. These capture areas where the seabeds lifted after the Kaikoura earthquake.</p>
<pre class="r"><code># Created AOI from the lidar raster extent
AOI &lt;- as(extent(kaikoura_lidar),&#39;SpatialPolygons&#39;) 
# Set the CRS to the lidar data proj4string
crs(AOI)@projargs &lt;- crs(kaikoura_lidar)@projargs
# Create a sf object
AOI_sf &lt;- st_as_sf(AOI)
# Set the CRS to EPSG 2193
AOI_sf &lt;- st_transform(AOI_sf,2193)</code></pre>
<pre class="r"><code># Check the crs of the transformed bbox
st_crs(AOI_sf)</code></pre>
<pre><code>## Coordinate Reference System:
##   No EPSG code
##   proj4string: &quot;+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs&quot;</code></pre>
<pre class="r"><code># We can check the bbox extent  of our reprojected sf object is in metres using st_bbox function
st_bbox(AOI_sf)</code></pre>
<pre><code>##    xmin    ymin    xmax    ymax 
## 1655200 5303040 1659520 5303760</code></pre>
<pre class="r"><code># Create a WKT from the bbox class using sf package
AOI_WKT &lt;- st_as_text(st_geometry(AOI_sf)) %&gt;%  
      data.frame()
# Write the WKT to file to be imported into QGIS
# write_csv(AOI_WKT,&quot;AOI_wkt.csv&quot;)</code></pre>
<pre class="r"><code># Set the EPSG to the native OSM EPSG 4326 https://rstudio.github.io/leaflet/projections.html for purposes of visualising the AOI rather than customing the leafletCRS to EPSG: 2193 
AOI_sf_4326 &lt;- st_transform(AOI_sf,4326)
# Map AOI using leaflet
m&lt;- AOI_sf_4326 %&gt;% 
      leaflet() %&gt;% 
      addTiles() %&gt;%
      addPolylines()
m</code></pre>
<div id="htmlwidget-2" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-2">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addPolylines","args":[[[[{"lng":[173.670985450106,173.670916320855,173.723418897906,173.723493435761,173.670985450106],"lat":[-42.4229890377847,-42.4165051587042,-42.4161858501577,-42.4226696571504,-42.4229890377847]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":false,"fillColor":"#03F","fillOpacity":0.2,"smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[-42.4229890377847,-42.4161858501577],"lng":[173.670916320855,173.723493435761]}},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code># Save htmlwidget for blog post
# htmlwidgets::saveWidget(m,&quot;AOI.html&quot;)</code></pre>
<p>Now convert the merged LiDAR raster to a dataframe.</p>
<pre class="r"><code># Convert the raster data to a dataframe
kaikoura_lidar_df &lt;- as.data.frame(kaikoura_lidar, xy = TRUE)</code></pre>
</div>
<div id="data-exploration" class="section level2">
<h2>Data Exploration</h2>
<p>Now plot the distribution of elevation values within the area of interest using our LiDAR raster data.</p>
<pre class="r"><code># plot histogram using ggplot
ggplot(kaikoura_lidar_df,aes(layer)) +
      geom_histogram()+
      ggtitle(&quot;Distribution of surface elevation values&quot;) +
      xlab(&quot;Elevation (meters)&quot;) + 
      ylab(&quot;Frequency&quot;) </code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 433655 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="https://kimnewzealand.github.io/post/KaikouraLIDARanalysis_files/figure-html/elevation%20histogram-1.png" width="672" /></p>
<pre class="r"><code># Find the highest point in the AOI
highest_point &lt;- kaikoura_lidar_df %&gt;% 
      top_n(1)</code></pre>
<pre><code>## Selecting by layer</code></pre>
<pre class="r"><code>highest_point</code></pre>
<pre><code>##         x       y layer
## 1 1656957 5303102 108.7</code></pre>
<p>From this histogram it seems this coastal land has some flat sea level land and steep sections to hilly viewpoints.</p>
<p>We could use LiDAR data from after the earthquake to measure the earth and seabed movements from the elevation differences if this data is made available by LINZ.</p>
</div>
<div id="data-visualisation" class="section level2">
<h2>Data Visualisation</h2>
<p>Let’s visualise the LiDAR raster in our AOI using base plot and levelplot from the <a href="https://cran.r-project.org/web/packages/rasterVis/index.html">rasterVis</a> R package.</p>
<pre class="r"><code># Use base plot to plot the lidar raster with the highest point
plot(kaikoura_lidar,sub=&quot;Source: LINZ CC 4.0&quot;) + title(&quot;Digital Elevation Model (DEM) Data \n Kaikoura, New Zealand \n Before the Earthquake in 2012&quot;)</code></pre>
<pre><code>## integer(0)</code></pre>
<pre class="r"><code>points(highest_point,col=&quot;green&quot;,pch = 19)</code></pre>
<p><img src="https://kimnewzealand.github.io/post/KaikouraLIDARanalysis_files/figure-html/plot%20lidar%20raster-1.png" width="672" /></p>
<pre class="r"><code># Plot levelplotusing rasterVis package
levelplot&lt;- levelplot(kaikoura_lidar, layers = 1, margin = list(FUN = &#39;median&#39;), contour=TRUE)
levelplot</code></pre>
<p><img src="https://kimnewzealand.github.io/post/KaikouraLIDARanalysis_files/figure-html/plot%20lidar%20raster-2.png" width="672" /></p>
<p>Now let’s view a recent satellite imagery so see what the sea beds look like now.</p>
<pre class="r"><code># Map AOI using leaflet with satellite basemap
m2 &lt;- AOI_sf_4326 %&gt;% 
      leaflet() %&gt;% 
      addTiles() %&gt;%
      addProviderTiles(providers$Esri.WorldImagery) %&gt;%
      addPolylines()
m2</code></pre>
<div id="htmlwidget-3" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-3">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addProviderTiles","args":["Esri.WorldImagery",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addPolylines","args":[[[[{"lng":[173.670985450106,173.670916320855,173.723418897906,173.723493435761,173.670985450106],"lat":[-42.4229890377847,-42.4165051587042,-42.4161858501577,-42.4226696571504,-42.4229890377847]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":false,"fillColor":"#03F","fillOpacity":0.2,"smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[-42.4229890377847,-42.4161858501577],"lng":[173.670916320855,173.723493435761]}},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code># htmlwidgets::saveWidget(m2,&quot;SatelliteAfterQuakes.html&quot;)</code></pre>
<p>We can see the raised sea beds from the earthquake in the leaflet satellite plot.</p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>This has been a great venture into using raster data and different coordinate systems. One of the main challenges with this type of data is that it is very big and so it is useful to know other tools such as QGIS.</p>
<p>Other lessons learnt include:</p>
<ul>
<li>Use base plot in R for initial visualisations of raster data as these data may be very large and using ggplot may just crash your PC.</li>
<li>Select the appropriate CRS up front in the data analysis and then reproject data. However reprojections of raster datasets can also be memory intensive. Using QGIS for on the fly projections are a good way to take a look at the data.</li>
<li>Most basic plots use the native OSM unprojected CRM system of WGS84. Since leaflet also defaults to this CRS, this would be the familiar starting point for first attempts at geospatial analysis.</li>
<li>Another way to view DEM’s is with 3D and there is so much more scope for playing with 3D R packages and other tools.</li>
</ul>
</div>


  
<div class="prev-next-post pure-g">
  <div class="pure-u-1-24" style="text-align: left;">
    
    <a href="https://kimnewzealand.github.io/2018/10/15/bike-counter/"><i class="fa fa-chevron-left"></i></a>
    
  </div>
  <div class="pure-u-10-24">
    
    <nav class="prev">
      <a href="https://kimnewzealand.github.io/2018/10/15/bike-counter/">Auckland Bike Counter Analysis</a>
    </nav>
    
  </div>
  <div class="pure-u-2-24">
    &nbsp;
  </div>
  <div class="pure-u-10-24">
    
  </div>
  <div class="pure-u-1-24" style="text-align: right;">
    
  </div>
</div>



  

</div>

</div>
</div>
<script src="https://kimnewzealand.github.io/js/ui.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-114904130-1', 'auto');
  ga('send', 'pageview');

</script>





</body>
</html>

