<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="generator" content="Hugo 0.31.1" />

  <title>Celestial Maps &middot; Kim Fitter</title>

  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/pure-min.css">

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-min.css">
  <!--<![endif]-->

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/side-menu-old-ie.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/side-menu.css">
  <!--<![endif]-->

  <link rel="stylesheet" href="https://kimnewzealand.github.io/css/blackburn.css">

  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

 
  

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/androidstudio.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  
  <script>hljs.initHighlightingOnLoad();</script>
  

  <link rel="shortcut icon" href="https://kimnewzealand.github.io/img/favicon.ico" type="image/x-icon" />

  
  

</head>


<body>
<div id="layout">

  
<a href="#menu" id="menuLink" class="menu-link">
  
  <span></span>
</a>
<div id="menu">

  
  <a class="pure-menu-heading brand" href="https://kimnewzealand.github.io/">Kim Fitter</a>


  <div class="pure-menu">
    <ul class="pure-menu-list">
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://kimnewzealand.github.io/"><i class='fa fa-home fa-fw'></i>Home</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://kimnewzealand.github.io/about/"><i class='fa fa-user fa-fw'></i>About</a>
      
        </li>
      
    </ul>
  </div>

  <div class="pure-menu social">
  <ul class="pure-menu-list">



    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://twitter.com/kim_fitter" target="_blank"><i class="fa fa-twitter-square fa-fw"></i>Twitter</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://github.com/kimnewzealand" target="_blank"><i class="fa fa-github-square fa-fw"></i>GitHub</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

  </ul>
</div>


  <div>
  <div class="small-print">
    <small>Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)</small>
  </div>
  <div class="small-print">
    <small>Built with&nbsp;<a href="https://gohugo.io/" target="_blank">Hugo</a></small>
    <small>Theme&nbsp;<a href="https://github.com/yoshiharuyamashita/blackburn" target="_blank">Blackburn</a></small>
  </div>
</div>

</div>


  <div id="main">


<div class="header">
  <h1>Celestial Maps</h1>
  <h2></h2>
</div>
<div class="content">

  <div class="post-meta">

  <div>
    <i class="fa fa-calendar fa-fw"></i>
    <time>21 Feb 2019</time>
  </div>

  

  

  
  
  
  <div>
    <i class="fa fa-tags fa-fw"></i>
    
      <a class="post-taxonomy-tag" href="https://kimnewzealand.github.io/tags/r">R</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="https://kimnewzealand.github.io/tags/geoviz">Geoviz</a>
    
  </div>
  
  

</div>

  <ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#import-data">Import Data</a></li>
<li><a href="#data-summary">Data Summary</a></li>
<li><a href="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
<li><a href="#data-cleaning">Data Cleaning</a></li>
<li><a href="#visualisations">Visualisations</a></li>
<li><a href="#conclusions">Conclusions</a></li>
<li><a href="#references">References</a></li>
</ul>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>While touring the New Zealand South Island with friends in January 2019, one of our stops was the <a href="https://mackenzienz.com/scenic-highlights/mountjohn/">The University of Canterbury Mt John Observatory</a>. Since it this area is a <a href="https://www.darksky.org/our-work/conservation/idsp/reserves/">dark sky reserve</a>, with a clear night and a new moon the midnight sky was lit up with stars and the milky way.</p>
<p>Inspired by our enthusiastic astrophysicist guide, Daniel, I thought that it would be relatively easy to replicate the evening sky chart in R and subsequently searched for R packages.</p>
<p>My initial searches (“plot the night sky rstats”) yielded no obvious results so I realised I had to learn some astronomical terminology.</p>
<p>According to Wikipedia <a href="https://en.wikipedia.org/wiki/Celestial_sphere">in astronomy and navigation, the celestial sphere</a>:</p>
<blockquote>
<p>is an imaginary sphere of arbitrarily large radius, concentric with the observer. All objects in the observer’s sky can be thought of as projected upon the inside surface of the celestial sphere, as if it were the underside of a dome or a hemispherical screen.</p>
</blockquote>
<p>This concept allows for visualising objects with no information of actual distances but objects appear to be on the sphere where the observer is appears to be still at the center.</p>
<p>So on Mt John we were observers looking at the night sky where <a href="https://www.skyandtelescope.com/astronomy-resources/what-are-celestial-coordinates/">the Earth</a></p>
<blockquote>
<p>is at the center of the celestial sphere, an imaginary surface on which the planets, stars, and nebulae seem to be printed. On the celestial sphere, lines of right ascension and declination are similar to longitude and latitude lines on Earth.</p>
</blockquote>
<p><a href="https://oneminuteastronomer.com/934/read-sky-coordinates/">Similar but different</a>. Declination is also in degrees but right ascension is however a measure of time in hours.</p>
<p>I then changed my search to “celestial map” and came across <a href="http://ofrohn.github.io/celestial-demo/">Celestial map with D3.js</a>. This website has some great <a href="http://ofrohn.github.io/celestial-demo/viewer.html">demos</a> and GeoJSON <a href="https://github.com/ofrohn/d3-celestial/tree/master/data">data sets</a> where</p>
<blockquote>
<p>For GeoJSON, all coordinates need to be given in degrees, longitude as [-180…180] deg, latitude as [-90…90] deg.</p>
</blockquote>
<p>Phew. At this point I realised I could remain at astronomy level=curiosity and not have to study space time in order to produce a map.</p>
<p>I decided to attempt to create celestial maps in R using the <a href="https://cran.r-project.org/web/packages/sf/index.html">sf</a> R package as this package can both read in and plot spatial data with the <a href="https://cran.r-project.org/web/packages/ggplot2/index.html">ggplot</a>.</p>
</div>
<div id="load-packages" class="section level2">
<h2>Load Packages</h2>
<pre class="r"><code>library(tidyverse)
library(rnaturalearthdata)
library(rnaturalearth)
library(sf)
# install.packages(&quot;devtools&quot;)
# devtools::install_github(&quot;yutannihilation/ggsflabel&quot;)</code></pre>
</div>
<div id="import-data" class="section level2">
<h2>Import Data</h2>
<div id="earth-data" class="section level3">
<h3>Earth data</h3>
<p>We can get earth data from the <a href="https://cran.r-project.org/web/packages/rnaturalearth/README.html">rnaturalearth</a> R package.</p>
<pre class="r"><code># Plot earth sphere using natural earth
earth &lt;- ne_countries(scale = &quot;medium&quot;, returnclass = &quot;sf&quot;)
class(earth)</code></pre>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<pre class="r"><code># Check the CRS of the earth
st_crs(earth)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code># Create a sf point object for the Mt John Observatory
mtjohn &lt;- st_point(c(170,-43)) %&gt;% # create an sfg object ( a vector) with the geometry type POINT from the Mt John coordinates https://en.wikipedia.org/wiki/Mount_John_University_Observatory
      st_sfc(crs=st_crs(earth)) %&gt;%   # convert to a geospatial  sfc object ( a list) with CRS set to the same as the earth sf object
      st_sf(name=&quot;Mt John Observatory&quot;) # Convert the geometry type POINT (a dataframe) with a CRS to an sf object and the point labelled with a name</code></pre>
</div>
<div id="celestial-data" class="section level3">
<h3>Celestial data</h3>
<p>Let’s read in the GeoJSON format <a href="https://github.com/ofrohn/d3-celestial/tree/master/data">celestial data</a> using the <a href="https://cran.r-project.org/web/packages/sf/index.html">sf</a> R package.</p>
<p>I initially tried geojsonR and geojsonio R packages but sf reads in data as am sf object.</p>
<pre class="r"><code>url1 &lt;- &quot;https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json&quot;
# Read in the constellation lines data using the st_read function
constellation_lines_sf &lt;- st_read(url1,stringsAsFactors = FALSE) </code></pre>
<pre><code>## Reading layer `constellations.lines&#39; from data source `https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json&#39; using driver `GeoJSON&#39;
## Simple feature collection with 89 features and 1 field
## geometry type:  MULTILINESTRING
## dimension:      XY
## bbox:           xmin: -177.9104 ymin: -83.6679 xmax: 179.9066 ymax: 89.2641
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<pre class="r"><code>url2 &lt;- &quot;https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/mw.json&quot;
# Read in the milky way data using the st_read function
milky_sf &lt;- st_read(url2,stringsAsFactors = FALSE)</code></pre>
<pre><code>## Reading layer `mw&#39; from data source `https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/mw.json&#39; using driver `GeoJSON&#39;
## Simple feature collection with 5 features and 1 field
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -179.987 ymin: -74.9 xmax: 180 ymax: 66.946
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<pre class="r"><code>url3 &lt;- &quot;https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json&quot;
# Read in the stars way data using the st_read function
stars_sf &lt;- st_read(url3,stringsAsFactors = FALSE)</code></pre>
<pre><code>## Reading layer `stars.6&#39; from data source `https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json&#39; using driver `GeoJSON&#39;
## Simple feature collection with 4560 features and 5 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -179.8148 ymin: -88.9565 xmax: 179.9871 ymax: 89.2641
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<p>The planets data is not geojson</p>
<blockquote>
<p>because positions need to be calculated by date from keplerian elements</p>
</blockquote>
<p>So again, to remain a novice in this domain, we will not use planet data in this exercise.</p>
</div>
</div>
<div id="data-summary" class="section level2">
<h2>Data Summary</h2>
<p>Let’s take a look at the <code>constellation_lines</code> object.</p>
<pre class="r"><code># Use dplyr glimpse to view the data summary
glimpse(constellation_lines_sf)</code></pre>
<pre><code>## Observations: 89
## Variables: 2
## $ id       &lt;chr&gt; &quot;And&quot;, &quot;Ant&quot;, &quot;Aps&quot;, &quot;Aqr&quot;, &quot;Aql&quot;, &quot;Ara&quot;, &quot;Ari&quot;, &quot;Aur...
## $ geometry &lt;MULTILINESTRING [Â°]&gt; MULTILINESTRING ((30.9748 4..., MULT...</code></pre>
<p>Let’s take a look at the <code>milky_sf</code> object.</p>
<pre class="r"><code># Use dplyr glimpse to view the data summary
glimpse(milky_sf)</code></pre>
<pre><code>## Observations: 5
## Variables: 2
## $ id       &lt;chr&gt; &quot;ol1&quot;, &quot;ol2&quot;, &quot;ol3&quot;, &quot;ol4&quot;, &quot;ol5&quot;
## $ geometry &lt;MULTIPOLYGON [Â°]&gt; MULTIPOLYGON (((97.754 34.6..., MULTIPO...</code></pre>
<p>Let’s take a look at the <code>stars_sf</code> object.</p>
<pre class="r"><code># Use dplyr glimpse to view the data summary
glimpse(stars_sf)</code></pre>
<pre><code>## Observations: 4,560
## Variables: 6
## $ name     &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;...
## $ desig    &lt;chr&gt; &quot;t&quot;, &quot;HD224865&quot;, &quot;&lt;U+03B8&gt;&quot;, &quot;HD224893&quot;, &quot;29&quot;, &quot;30&quot;, &quot;85&quot;, &quot;...
## $ con      &lt;chr&gt; &quot;Phe&quot;, &quot;&quot;, &quot;Oct&quot;, &quot;&quot;, &quot;Psc&quot;, &quot;Psc&quot;, &quot;Peg&quot;, &quot;Scl&quot;, &quot;Ps...
## $ mag      &lt;dbl&gt; 5.8690, 5.6243, 4.9354, 5.6725, 5.0831, 4.4120, 5.873...
## $ bv       &lt;chr&gt; &quot;0.911&quot;, &quot;1.615&quot;, &quot;1.254&quot;, &quot;0.407&quot;, &quot;-0.128&quot;, &quot;1.631&quot;...
## $ geometry &lt;POINT [Â°]&gt; POINT (0.2691 -48.8099), POINT (0.3338 -50.337...</code></pre>
<p>There are a large number of stars for a plot. We may need to filter the dataset in our plots.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<div id="night-sky-theme-for-plots" class="section level3">
<h3>Night Sky Theme for Plots</h3>
<p>First create a custom theme function called <code>theme_nightsky</code> to use for all our plots.</p>
<pre class="r"><code># Use this custom function as a starting point to the format of the theme function https://jonlefcheck.net/2013/03/11/black-theme-for-ggplot2-2/

theme_nightsky &lt;- function(base_size = 11, base_family = &quot;&quot;) {

  theme_light(base_size = base_size, base_family = base_family) %+replace% 
      theme(
      # Specify axis options, remove both axis titles and ticks but leave the text in white
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_text(colour = &quot;white&quot;,size=6),
      # Specify legend options, here no legend is needed
      legend.position = &quot;none&quot;,
      # Specify background of plotting area
      panel.grid.major = element_line(color = &quot;grey35&quot;),  
      panel.grid.minor = element_line(color = &quot;grey20&quot;),  
      panel.spacing = unit(0.5, &quot;lines&quot;),
      panel.background = element_rect(fill = &quot;black&quot;, color  =  NA),  
      panel.border = element_blank(),  
      # Specify plot options
      plot.background = element_rect( fill = &quot;black&quot;,color = &quot;black&quot;),  
      plot.title = element_text(size = base_size*1.2, color = &quot;white&quot;),
      plot.margin = unit(rep(1, 4), &quot;lines&quot;)
    )
 
}</code></pre>
</div>
</div>
<div id="location-of-the-observatory" class="section level2">
<h2>Location of the Observatory</h2>
<p>Let’s use this new theme to plot the earth data <code>earth</code> with the approximate location of the Mt John Observatory. We will keep the CRS of <code>earth</code> object as the default 4326, +proj=longlat +datum=WGS84 +no_defs. Use <a href="https://cran.r-project.org/web/packages/ggplot2/index.html">ggplot</a>,<a href="https://cran.r-project.org/web/packages/sf/">sf</a> and <a href="https://yutannihilation.github.io/ggsflabel/index.html">ggsflabel</a> R package to label the <code>sf</code> geometry objects.</p>
<p>Although we have a theme, we still need to specify colours for the geoms. Additionally notice that the colour parameters are not included as aesthetics in the <code>geom_sf</code> code and the <code>geom_sf</code> function needs parameter <a href="https://www.jessesadler.com/post/gis-with-r-intro/">data =</a> included.</p>
<pre class="r"><code># Plot the earth using ggplot and sf
ggplot() +
      geom_sf(data = earth) +
      geom_sf(data = mtjohn,colour=&quot;yellow&quot;,size=2)+
      theme_nightsky()+
      ggsflabel::geom_sf_text_repel(data= mtjohn,
                   aes(label=mtjohn$name),
                   nudge_x = -1, 
                   nudge_y=-1,
                   colour=&quot;yellow&quot;,
                   size=4)</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/earth%20plot-1.png" width="672" /></p>
<div id="milky-way-plot" class="section level3">
<h3>Milky way plot</h3>
<p>Use ggplot to plot the <code>milky_sf</code> object which is a sfc_MULTIPOLYGON, sfc.</p>
<pre class="r"><code># Use ggplot to plot the milky way
milky_sf  %&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/milky%20plot-1.png" width="672" /></p>
<p>This plot has a few horizontal lines ?!? The polygons may be crossing -180 to 180 longitude.</p>
</div>
<div id="stars-plot" class="section level3">
<h3>Stars plot</h3>
<p>Use <code>ggplot</code> to plot the <code>stars_sf</code> object which is a sfc_POINT, sfc. Incidently the brightest star has a negative magnitude value, which refers to <a href="https://earthsky.org/astronomy-essentials/what-is-stellar-magnitude">apparent visual magnitude</a>. We will need to convert this to a new <code>newmag</code> value in order to plot sizes to a scale from smallest to largest.</p>
<pre class="r"><code># Extract the constellation stars with names
stars_con_sf&lt;- stars_sf %&gt;%  
      filter(name!=&quot;&quot;) %&gt;%  
      filter(con!=&quot;&quot;)
# Extract the brightest constellation stars with names, with an arbitrary cutoff 0.5 for mag - this extracts the top 10 brightest stars
stars_bright_sf&lt;- stars_con_sf %&gt;% 
      filter(mag&lt;0.5)
# Change the mag to a new scale newmag for the size aesthetic
stars_bright_sf&lt;-stars_bright_sf %&gt;% 
      mutate(newmag=-(mag-1.1)/4)
# Use ggplot to plot the brighest stars by constellation
stars_bright_sf %&gt;% 
      ggplot()+
      # Group the stars by constellation
      geom_sf(aes(size=newmag,fill=con,colour=con))+
      geom_sf_text(aes(label=name), colour=&quot;white&quot;)+
      theme_nightsky()+
      # In this case add a legend to see the constellations and new magnitudes
      theme(legend.position=&quot;right&quot;)</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/stars%20plot-1.png" width="672" /></p>
</div>
<div id="constellation-lines-plot" class="section level3">
<h3>Constellation lines plot</h3>
<p>Use ggplot to plot the <code>constellation_lines_sf</code> object which is a sfc_MULTILINESTRING, sfc.</p>
<pre class="r"><code># Use ggplot to plot the constellation lines
constellation_lines_sf %&gt;%  
      ggplot()+
      geom_sf(colour=&quot;white&quot;)+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/constellation%20lines%20plot-1.png" width="672" /></p>
<p>Again there are horizontal lines. We will look to clean the data to resolve the dateline issue in the next section.</p>
</div>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data Cleaning</h2>
<p>Let’s look into ways to fix the horizontal lines.</p>
<div id="set-extent" class="section level3">
<h3>Set Extent</h3>
<p>Take a look at the Virgo Constellation, which has a horizontal line.</p>
<pre class="r"><code># Take a look at a constellation with a very broad range of longitudes
constellation_lines_sf %&gt;%  
      filter(id==&quot;Vir&quot;) %&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/virgo%20plot%20extent-1.png" width="672" /></p>
<pre class="r"><code># Try to remove the lines by setting extent
 constellation_lines_sf %&gt;%  
      filter(id==&quot;Vir&quot;) %&gt;% 
      ggplot()+
      geom_sf() +
      # Set the extent of the map using coord_sf
      coord_sf(xlim = c(-180,170),expand=FALSE)+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/virgo%20plot%20extent-2.png" width="672" /></p>
<p>Although the extent has been reduced, there is still a horizontal line.</p>
</div>
<div id="crop-the-data-sets" class="section level3">
<h3>Crop the data sets</h3>
<p>In order to crop the data, first convert the constellation lines data into points.</p>
<pre class="r"><code># Create points of the constellation lines
constellation_lines_sf_p &lt;-constellation_lines_sf %&gt;%  
      # cast the MULTILINESTRING TO MULTIPOINT
      st_cast(&quot;MULTIPOINT&quot;)

# Create a table with the X,Y coordinates
(coords &lt;- constellation_lines_sf_p %&gt;%  
      filter(id==&quot;Vir&quot;) %&gt;% 
      st_coordinates() %&gt;% 
      as.data.frame() )</code></pre>
<pre><code>##            X        Y L1
## 1   176.4648   6.5294  1
## 2   177.6738   1.7647  1
## 3  -175.0235  -0.6668  1
## 4  -169.5848  -1.4494  1
## 5  -162.5125  -5.5390  1
## 6  -158.7018 -11.1613  1
## 7  -145.9964  -6.0005  1
## 8  -139.2349  -5.6582  1
## 9  -164.4558  10.9592  2
## 10 -166.0991   3.3975  2
## 11 -169.5848  -1.4494  2
## 12 -162.5125  -5.5390  3
## 13 -156.3267  -0.5958  3
## 14 -149.5884   1.5445  3
## 15 -138.4378   1.8929  3</code></pre>
<pre class="r"><code># Check the range of the coords
range(coords$X)</code></pre>
<pre><code>## [1] -175.0235  177.6738</code></pre>
<pre class="r"><code>range(coords$Y)</code></pre>
<pre><code>## [1] -11.1613  10.9592</code></pre>
<pre class="r"><code># Plot the points of Virgo to visualise this new point geometry
constellation_lines_sf_p %&gt;%
      filter(id==&quot;Vir&quot;) %&gt;% 
      ggplot()+
      geom_sf(colour=&quot;white&quot;) +
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/makes%20points-1.png" width="672" /></p>
<pre class="r"><code># Crop points then convert back to a MULTILINESTRING for one id Vir and visualise
constellation_lines_sf_p%&gt;% 
      filter(id==&quot;Vir&quot;) %&gt;% 
#     https://github.com/r-spatial/sf/issues/720
      st_crop(xmin=-180,xmax=175,ymin=-180,ymax=180) %&gt;%
      group_by( id )  %&gt;% 
      # Cast POINTS to LINESTRING
      st_cast(&quot;LINESTRING&quot;) %&gt;%
      # Combine the LINESTRINGS into a single row as MULTILINESTRING sfc, however the id feature is now lost
      st_combine()  %&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersection assumes that they are planar</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/crop%20data-1.png" width="672" /></p>
<pre class="r"><code># Create a linestring function based on this example
to_linestring &lt;- function(x)  st_cast(x,&quot;LINESTRING&quot;) %&gt;% 
      st_combine() %&gt;%  .[[1]]
      
# Crop the points based on and y min and max
constellation_lines_sf_cropped&lt;-constellation_lines_sf_p %&gt;% 
      st_crop(xmin=-180,xmax=169,ymin=-180,ymax=180) %&gt;%
      dplyr::group_by(id)%&gt;% 
      # Create a list of data variable using nest function https://www.r-spatial.org/r/2017/08/28/nest.html
      tidyr::nest()</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersection assumes that they are planar</code></pre>
<pre class="r"><code># Convert the points to lines
newlines &lt;- constellation_lines_sf_cropped %&gt;%
       # Since data is a list we cannot use select so use pull which is like [[ to extract the data variable list
      pull(data) %&gt;% 
      map(to_linestring)  %&gt;% 
      st_sfc(crs = st_crs(earth))

# This error came up as we tried to run the function on the cropped data:Error in st_cast.POINT(X[[i]], ...) : cannot create LINESTRING from POINT. Turns out the function was creating single points which could not be cast to lines
constellation_lines_sf_new &lt;- constellation_lines_sf_cropped %&gt;% 
      select(-data) %&gt;% 
      st_sf(geometry = newlines)

# Plot cropped constellation lines
constellation_lines_sf_new %&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/crop%20data-2.png" width="672" /></p>
<p>The Virgo constellation has been cropped and now doesn’t have the horizontal line. However some other constellations still have the lines.</p>
<p>This data cleaning method has a couple of downsides.It removes data creating data quality issues, for example if the globe is rotated then there would be lines missing and it is time intensive manual process.</p>
<p>Let’s look for a different approach.</p>
</div>
<div id="coordinate-analysis" class="section level3">
<h3>Coordinate Analysis</h3>
<p>Let’s extract and analyse the coordinates of the horizontal lines in <code>milky_sf</code> that are creating the unexpected horizontal lines.</p>
<pre class="r"><code># Extract the coordinates from the milk_sf object
milkycoords &lt;- milky_sf %&gt;%
      st_coordinates() %&gt;% 
      as.data.frame() 

# Identify the coordinates where the X coordinate has crossed from + to - or from - to +
firstX &lt;- milkycoords[1,1]
(milkycoords_cross &lt;- milkycoords %&gt;% 
      mutate(prevXval=ifelse(X!=firstX,lag(X),0)) %&gt;% 
      mutate(prevYval=ifelse(X!=firstX,lag(Y),0))%&gt;% 
      mutate(prevL1=ifelse(X!=firstX,lag(L1),0))%&gt;% 
      mutate(cross=ifelse(L1!=prevL1,&quot;NOCROSS&quot;, # check diff L1 object first
            ifelse(prevXval&gt;0, ifelse(X&gt;0,&quot;NOCROSS&quot;, # X and prevval pos
                  &quot;CROSS&quot;), # X is pos and prevval is neg
                  ifelse(X&lt;0,&quot;NOCROSS&quot;,  # X and prevval both neg
                        &quot;CROSS&quot;) ))) %&gt;% # X is neg and prevval pos 
      select(-L1,-L2,-L3,-prevL1) %&gt;% 
      filter(cross==&quot;CROSS&quot;) %&gt;% 
      select(-cross) )</code></pre>
<pre><code>##           X       Y prevXval prevYval
## 1    -0.121  65.001    0.067   65.117
## 2   180.000 -50.039 -179.879  -50.156
## 3    -0.075  47.787    0.038   47.904
## 4   179.754 -73.960 -179.900  -73.979
## 5    -0.012  60.529    0.146   60.646
## 6     0.092  63.999   -0.133   63.981
## 7  -179.929 -58.704  179.883  -58.686
## 8   179.846 -66.118 -179.958  -66.236
## 9  -179.742 -65.234  179.979  -65.314
## 10  179.783 -64.687 -179.987  -64.706
## 11 -179.842 -61.156  179.992  -61.039
## 12  179.867 -63.981 -179.867  -63.901</code></pre>
<pre class="r"><code># Create a function that creates a linestring that extracts vectors (using the as.numeric fn) of the X,Y and prevXval, prevYval points from nx4 dataframe, then bind to a matrix 
make_line &lt;- function(x) {rbind(as.numeric(milkycoords_cross[x,1:2]),
                              as.numeric(milkycoords_cross[x,3:4]))%&gt;%
            # Convert to a linestring object
            st_linestring()   %&gt;% 
            st_sfc(crs=st_crs(earth)) %&gt;% 
      # Convert to a geospatial  sfc object ( a list) with CRS set to the same as the earth sf object
      st_sf()
}

# Check function works on the first set of points
make_line(1)</code></pre>
<pre><code>## Simple feature collection with 1 feature and 0 fields
## geometry type:  LINESTRING
## dimension:      XY
## bbox:           xmin: -0.121 ymin: 65.001 xmax: 0.067 ymax: 65.117
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
##                         geometry
## 1 LINESTRING (-0.121 65.001, ...</code></pre>
<pre class="r"><code># I could not find a way to get the function to apply over rows so I posted this question https://gis.stackexchange.com/questions/312289/r-create-multiple-linestrings-from-multiple-coordinates

# The key here was to use matrix functionality to reshape the coordinates and then convert the dataframe rows into a list so that purrr could iterate over the list

# Now create an sf object with all the lines 
milkyhorizlines_sf &lt;- map(split(milkycoords_cross, seq(nrow(milkycoords_cross))), function(row) {
    matrix(unlist(row[1:4]), ncol = 2, byrow = TRUE) %&gt;% 
            st_linestring()
  }) %&gt;%  
      st_sfc(crs=st_crs(earth))  %&gt;% 
      st_sf() %&gt;% 
      # Cast to MULTILINESTRING to avoid Error in CPL_geos_is_empty(st_geometry(x)) :
      st_cast(&quot;MULTILINESTRING&quot;) 

# Plot the horizontal lines only
milkyhorizlines_sf %&gt;% 
    ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/milky%20horiz%20lines%20analysis-1.png" width="672" /></p>
<p>Potentially the <code>milkyhorizlines_sf</code> could be plotted over in black to hide the lines. However this would work for lines however it may not work with polygons if they are filled.</p>
</div>
<div id="wrap-date-line" class="section level3">
<h3>Wrap Date Line</h3>
<p>There is also an sf function <a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_wrap_dateline</a> to <a href="https://gis.stackexchange.com/questions/295158/r-sptransform-polygon-that-crosses-dateline">transform a polygon that crosses the dateline</a>. This appears to be the better approach as there is no potential data removal and it involves a simpler function to the previous approaches.</p>
<pre class="r"><code># Try to remove the lines by st_wrap_dateline function
 constellation_lines_sf %&gt;%  
  st_wrap_dateline(options = c(&quot;WRAPDATELINE=YES&quot;, &quot;DATELINEOFFSET=180&quot;))%&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/wrap_dateline%20con%20lines-1.png" width="672" /></p>
<p>This appears to work for the <code>constellation lines</code> so we will use a transformed object in the final plot for <code>constellation_lines</code>.</p>
<pre class="r"><code># Transform the  constellation_lines_sf
constellation_lines_sf_trans &lt;- constellation_lines_sf %&gt;%  
  st_wrap_dateline(options = c(&quot;WRAPDATELINE=YES&quot;, &quot;DATELINEOFFSET=180&quot;)) %&gt;% 
      st_cast(&quot;MULTILINESTRING&quot;)</code></pre>
<p>Let’s apply this function to the <code>milky_sf</code> object.</p>
<pre class="r"><code># Try to remove the lines by st_wrap_dateline function
milky_sf  %&gt;% 
      st_cast(&quot;MULTILINESTRING&quot;) %&gt;% 
  st_wrap_dateline(options = c(&quot;WRAPDATELINE=YES&quot;, &quot;DATELINEOFFSET=0&quot;)) %&gt;% 
      ggplot()+
      geom_sf()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/wrap_dateline%20milky-1.png" width="672" /></p>
<p>This appears to work for the <code>milky_sf</code> so we will use a transformed object in the final plot.</p>
<pre class="r"><code># Transform milky_sf with st_wrap_dateline
milky_sf_trans &lt;- milky_sf %&gt;% 
      # These polygons have errrors with the st_wrap_dateline so add a cast to MULTILINESTRING then LINESTRING to break it up smaller
       st_cast(&quot;MULTILINESTRING&quot;) %&gt;%  
       st_cast(&quot;LINESTRING&quot;) %&gt;%
       group_by(id)%&gt;%  
       st_wrap_dateline(options = c(&quot;WRAPDATELINE=YES&quot;, &quot;DATELINEOFFSET=180&quot;)) 
      
# Convert the milky way back to MULTIPOLYGON so it will fill with grey in the plots, the outer od1 lines are on the 180 and -180 so we need to treat these separately using  to the other lines which we can convert to MULTIPOLYGON
milky_sf_trans[3:202,]&lt;- milky_sf_trans[3:202,] %&gt;% 
      st_cast(&quot;MULTIPOLYGON&quot;)
# Use concaveman R package https://github.com/joelgombin/concaveman or https://gis.stackexchange.com/questions/290170/convert-a-linestring-into-a-closed-polygon-when-the-points-are-not-in-order to create a polygon of the outer milky way
milky_sf_transclosed &lt;- concaveman::concaveman(milky_sf_trans[1:2,])
# Now plot these transformed objects to check
ggplot() +
     geom_sf(data = milky_sf_transclosed,alpha=0.9,aes(fill=id))+
     geom_sf(data = milky_sf_trans,alpha=0.4,aes(fill=id)) +
     # Fill the milky way - inversely plot the discrete polygon values from light grey in the center
      scale_fill_grey()+
      theme_nightsky()</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/transform%20milk-1.png" width="672" /></p>
</div>
<div id="reprojecting-the-crs" class="section level3">
<h3>Reprojecting the CRS</h3>
<p>Since we are mapping the night sky let’s find an ellipsoidal projection rather than the default projection 4326, +proj=longlat +datum=WGS84 +no_defs. Reviewing the excellent <a href="https://geocompr.robinlovelace.net/intro.html">Geocomputation for R</a>, we discover the <a href="https://en.wikipedia.org/wiki/Mollweide_projection">Mollweide projection</a> preserves area relationships and one of its applications is global maps of the night sky. An alternative is the <a href="http://auger.org/education/Auger_Education/Aitoff.html">Aitoff</a> projection but this creates a GDAL error in <code>st_transform()</code> so it does not appear available with <code>sf</code> at the moment.</p>
<pre class="r"><code># Check the CRS of the stars, constellation and milky way objects
st_crs(stars_sf)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code>st_crs(stars_bright_sf)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code>st_crs(constellation_lines_sf_trans)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code>st_crs(milky_sf_trans)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<pre class="r"><code>st_crs(milky_sf_transclosed)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<p>The star maps objects have been loaded with CRS 4326, +proj=longlat +datum=WGS84 +no_defs, the same CRS 4326, +proj=longlat +datum=WGS84 +no_defs as the earth object.</p>
<pre class="r"><code># Transform stars_sf to Mollweide CRS
stars_sf&lt;- st_transform(stars_sf, crs = &quot;+proj=moll&quot;)

# Transform stars_bright_sf to Mollweide CRS
stars_bright_sf&lt;- st_transform(stars_bright_sf, crs = &quot;+proj=moll&quot;)

# Transform constellation_lines_sf_trans to Mollweide CRS
constellation_lines_sf_trans&lt;- st_transform(constellation_lines_sf_trans, crs = &quot;+proj=moll&quot;)

# Transform milky_sf_trans to Mollweide CRS
milky_sf_trans&lt;- st_transform(milky_sf_trans, crs = &quot;+proj=moll&quot;)

# Transform milky_sf_trans to Mollweide CRS
milky_sf_transclosed&lt;- st_transform(milky_sf_transclosed, crs = &quot;+proj=moll&quot;)

# Let&#39;s take a look at the new CRS of one of the objects
st_crs(milky_sf_trans)</code></pre>
<pre><code>## Coordinate Reference System:
##   No EPSG code
##   proj4string: &quot;+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs&quot;</code></pre>
</div>
</div>
<div id="visualisations" class="section level2">
<h2>Visualisations</h2>
<div id="brightest-stars" class="section level3">
<h3>10 Brightest Stars</h3>
<p>Since the number of objects in the universe is so large,to create a plot as introductory first look at a celestial map, let’s first take a look at the 10 brightest stars. Use <code>ggplot</code> and <code>sf</code> R packages.</p>
<p>We will start with a simplified plot of the 10 brightest stars to minimise cognitive load on a person looking at a celestial map for the first time. Although stars can be different colours but this subject itself is too complex to explain in one plot. We will therefore use our black and white theme“. For the plot colours, use different <a href="https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf">greys</a> to soften the contrast of black and white. The sizing of the stars is not to scale but they provide an idea of size and positioning relative to each other. The other constellation stars are plotted as small white dots on a globe with graticules to provide further visual clues that this is a star map. The tooltips provide information on the star name, magnitude and constellation to encourage further research or reading.</p>
<p>First create the ggplot object.</p>
<pre class="r"><code># Create a ggplot object and use the hover text functionality.
(starplot1 &lt;- ggplot() +
      geom_sf(data = milky_sf_transclosed,
              alpha=0.2,
              aes(fill=id))+
      geom_sf(data = milky_sf_trans,
              alpha=0.4,
              aes(fill=id)) +
      # Plot the constellation stars  as small white dots
      geom_sf(data=stars_sf, 
              colour=&quot;grey60&quot;,
              size=0.2) +
      # Now plot the bright stars
      geom_sf(data=stars_bright_sf,  
              colour=&quot;grey88&quot;, 
              aes(size=stars_bright_sf$newmag, 
                  text=paste(&#39;&lt;/br&gt;Name: &#39;,name,&#39;&lt;/br&gt;Stellar Magnitude: &#39;,mag,&#39;&lt;/br&gt;Constellation: &#39;,con)))  +
      # Fill the milky way - inversely plot the discrete polygon values from light grey in the center
      scale_fill_grey()+
      theme_nightsky()+
      ggtitle(&quot;The 10 Brightest Stars&quot;) )</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/star%20plot-1.png" width="672" /></p>
<pre class="r"><code># Now add the labels with star names
(starplot1_labels &lt;- starplot1 +
      ggsflabel::geom_sf_text_repel(data= stars_bright_sf,
                   aes(label=stars_bright_sf$name),
                        nudge_x = -2, 
                   colour=&quot;white&quot;,
                   size=2.5))</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/star%20plot-2.png" width="672" /></p>
<pre class="r"><code># Save ggplot for blog post
# ggsave(&quot;starplot1_labels.jpg&quot;,starplot1_labels)</code></pre>
</div>
</div>
<div id="celestial-map-with-more-objects" class="section level2">
<h2>Celestial Map with More objects</h2>
<p>Now use <code>ggplot</code>, <code>sf</code> and <code>ggsflabel</code> again to plot a star map with more objects for someone who would like to know more about the sky, including the constellations. This time we use other colours to label the objects as this one is a lot busier.</p>
<pre class="r"><code># Plot the stars,constellations and milky way with a starplot ggplot object.
starplot2&lt;- ggplot() +
     geom_sf(data = milky_sf_trans,alpha=0.4,aes(fill=id)) +
     # Fill the milky way - inversely plot the discrete polygon values from light grey in the center
      scale_fill_grey()+ 
      # Plot the consteallation stars as small white dots. Stars actually have different colours white, red etc but in this case we will keep to ablack and white theme
      geom_sf( data=stars_sf, colour=&quot;lightgrey&quot;,size=0.1) +
      # Now plot the bright stars
      geom_sf(data=stars_bright_sf,  colour=&quot;white&quot;, aes(size=stars_bright_sf$newmag) ) + 
      geom_sf(data =constellation_lines_sf_trans, alpha=0.2, colour=&quot;lightgrey&quot;)  +
      theme_nightsky()+
      ggtitle(&quot;Constellations, Stars and the Milky Way&quot;) 
# Plot the starplot2 with the labels
starplot2+
      ggsflabel::geom_sf_text_repel(data= stars_bright_sf,
                   aes(label=stars_bright_sf$name),
                        nudge_x = -2, 
                   colour=&quot;yellow&quot;,
                   size=2.5)+      
     ggsflabel::geom_sf_text_repel(data= constellation_lines_sf,
                   aes(label=constellation_lines_sf$id),
                        nudge_x = -1, 
                   colour=&quot;lightblue&quot;,
                   size=2)</code></pre>
<p><img src="https://kimnewzealand.github.io/post/celestialmaps_files/figure-html/starplot2-1.png" width="672" /></p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>From the tour and subsequently analysing this data, here are some things I learnt about the stars:</p>
<ul>
<li>Sirius is the <a href="http://blog.simulationcurriculum.com/articles/2015/5/15/the-ten-brightest-stars-in-the-sky">brightest star</a> in the constellation Canis Major, a white dwarf and is commonly know as the Dog Star, followed by the second brightest star, Canopus.</li>
<li>Alpha Centauri is also known as Rigel Kentaurus, and actually a system of three stars Alpha Centauri A, Alpha Centauri B and Alpha Centauri C.</li>
<li>In <a href="https://earthsky.org/astronomy-essentials/what-is-stellar-magnitude">stellar apparent visual magnitude</a>, the brighter objects have higher negative numbers and the fainter have higher positive numbers.</li>
</ul>
<p>This exercise involved more data manipulation than I expected but it has been great data structure thinking practice.</p>
<p>Packages like <code>sf</code> and <code>purrr</code> use lists and it is often a good solution to a problem to convert data into a list first, then iterate over the list. This can be done with functions like <code>nest</code> and <code>split</code>. Additionally matrix functionality can be used to reshape a dataframe.</p>
<p>Although I spent a LOT of time thinking thinking through the dateline issue, I discovered the <code>st_wrap_dateline</code> which is a great addition to the toolkit for the next horizontal lines issue.</p>
</div>
<div id="other-tools-for-sky-maps" class="section level2">
<h2>Other Tools for Sky Maps</h2>
<p>Here are some other tools to produce planetarium type looking up at the sky maps.</p>
<ul>
<li><a href="https://in-the-sky.org/skymap2.php">In the sky</a></li>
<li><a href="https://theskylive.com/planetarium">The Sky Live</a></li>
<li><a href="https://www.google.com/sky/about.html#sources">Google sky</a></li>
</ul>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<ul>
<li><a href="https://github.com/ofrohn/d3-celestial/tree/master/data">d3-celestial data</a> includes citations to source data.<br />
</li>
<li><a href="https://geocompr.robinlovelace.net/intro.html">Geocomputation for R</a><br />
</li>
<li><a href="http://blog.simulationcurriculum.com/articles/2015/5/15/the-ten-brightest-stars-in-the-sky">The Ten Brightest Stars in the Sky</a><br />
</li>
<li><a href="https://earthsky.org/astronomy-essentials/what-is-stellar-magnitude">Stellar magnitude</a></li>
</ul>
</div>


  
<div class="prev-next-post pure-g">
  <div class="pure-u-1-24" style="text-align: left;">
    
    <a href="https://kimnewzealand.github.io/2019/01/31/animation-basketball/"><i class="fa fa-chevron-left"></i></a>
    
  </div>
  <div class="pure-u-10-24">
    
    <nav class="prev">
      <a href="https://kimnewzealand.github.io/2019/01/31/animation-basketball/">Animation of Basketball Shots</a>
    </nav>
    
  </div>
  <div class="pure-u-2-24">
    &nbsp;
  </div>
  <div class="pure-u-10-24">
    
    <nav class="next">
      <a href="https://kimnewzealand.github.io/2019/03/02/why-blog/">Why blog?</a>
    </nav>
    
  </div>
  <div class="pure-u-1-24" style="text-align: right;">
    
    <a href="https://kimnewzealand.github.io/2019/03/02/why-blog/"><i class="fa fa-chevron-right"></i></a>
    
  </div>
</div>



  

</div>

</div>
</div>
<script src="https://kimnewzealand.github.io/js/ui.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-114904130-1', 'auto');
  ga('send', 'pageview');

</script>





</body>
</html>

